### ISSUE TITLE
关于error问题请教

### ISSUE THREAD

**Issue by YangPeaceLove** [weibocom/motan-go#103]
线上会不定时出现如下错误，一出现就会批量出现好多条
“No referers for request, RequestID: 0, Request info: map[M_g:motan-demo-rpc3 M_mdu: M_v: M_s:ray-test]”。
这个什么情况下会导致，该如何排查呢？
多谢！

**Comment by YangPeaceLove** [comment]
是会有Referer disable这样的日志。请教下该怎么处理呢？麻烦了！

**Comment by Zha-Zha** [comment]
你贴一下你的info和error日志，可以在日志中排查问题

**Comment by YangPeaceLove** [comment]
info的日志：（因为有大量的超时处理，这里的日志超时的比较多，差不多是重复如下4条）
I1017 16:03:50.493709   29559 motanEndpoint.go:174] Referer disable:motan2://127.0.0.1:8100/com.weibo.motan2.test.Motan3TestService?group=motan-demo-rpc3
W1017 16:03:50.503614   29559 motanEndpoint.go:517] handle recv message, missing stream: 1539763430409924452, ep:127.0.0.1:8100
W1017 16:03:50.493729   29559 failoverHA.go:41] FailOverHA call fail! url:motan2://127.0.0.1:8100/com.weibo.motan2.test.Motan3TestService?group=motan-demo-rpc3, err:&{ErrCode:400 ErrMsg:channel call error:Timeout err: receive request timeout ErrType:1}
E1017 16:03:50.496895   29559 motanEndpoint.go:145] motanEndpoint call fail. ep:127.0.0.1:8100, req:req{0,com.weibo.motan2.test.Motan3TestService,SearchMt}, msgid:1539763430446624635, error: Timeout err: receive request timeout

**Comment by YangPeaceLove** [comment]
error日志，都是“error: Timeout err: receive request timeout”的日志。（这边使用的时候设置了请求的超时时间，所以这个错误可以理解吧）

**Comment by YangPeaceLove** [comment]
请问下，server端一检测到超时就会导致endpoint熔断嘛？还有超过几次之后才会导致熔断的？

**Comment by Zha-Zha** [comment]
连续调用10次失败后就会熔断，熔断时间默认10秒，10秒后继续检测endpoint状态：
1. 如果可用，则恢复endpoint，并会打info日志`[keepalive] heartbeat success. url:`
2. 如果依然不可用，则继续熔断，并会打info日志`[keepalive] heartbeat failed. url:`，或`[keepalive] failed. url:`

**Comment by YangPeaceLove** [comment]
如果我的使用场景client调用timeout了我不管它(本身配置文件requestTimeout: 50，能成功就成功，不能成功也无所谓的情况下)，我是不是可以把10次改大一些。有一些timeout的情况出现，但是连接什么的都是正常的是吧

**Comment by Zha-Zha** [comment]
endpoint的熔断策略目前是写死的，不支持定制
我们后续会加一个降级开关，关闭熔断策略

**Comment by YangPeaceLove** [comment]
我直接改代码把defaultErrorCountThreshold由10改成100。就是连续出现timeout 100次，才会判断成熔断是吧。这样就会减少上面error的问题了是吧

**Comment by Zha-Zha** [comment]
这是能生效的，但只是个临时方案
我们后续会提供一个全局开关，可以关掉这个功能

**Comment by YangPeaceLove** [comment]
从昨晚改完到现在 一直没有出现过上面的error(主要是业务场景导致会有一些timeout的情况)。非常感谢大佬的响应和支持，多谢！
