### ISSUE TITLE
感觉配置项略复杂了

### ISSUE THREAD

**Issue by cye1024** [weibocom/motan-go#11]
跑了一下demo，感觉配置项稍微有点复杂了，希望有所简化。
好像是java-style的使用方式。因为之前没用过java，所以不太适应。

**Comment by rayzhang0603** [comment]
嗯，配置确实有些java-style，这里的初衷是希望和java版本的配置基本保持一致。这样不同语言的使用者沟通起来会更容易一些。
如果有什么好的配置方式，欢迎提建议，我们会认真考虑是否适合。
