### ISSUE TITLE
麻烦提供一下client请求中，多参数，复杂参数（复杂结构体）的例子

### ISSUE THREAD

**Issue by cye1024** [weibocom/motan-go#13]
谢谢

**Comment by rayzhang0603** [comment]
目前还不支持复杂参数，后续的版本将会支持，敬请关注。
多参数、复杂参数其实与框架自身关系不大，主要在序列化扩展上，目前simple序列化主要为解决restful接口迁移，后续会支持PB与hprose序列化。也非常欢迎PR:)
