### ISSUE TITLE
motan-go是只支持simple编码格式么？

### ISSUE THREAD

**Issue by cye1024** [weibocom/motan-go#14]
有simple格式的说明么？

**Comment by rayzhang0603** [comment]
[simple协议说明](https://github.com/weibocom/motan-go/wiki/zh_userguide#simple序列化) 。 目前只支持simple，grpc协议和PB序列化、hprose序列化都在近期的开发列表中。

**Comment by cye1024** [comment]
预计什么时候能支持复杂、多参数呢？如果时间比较长的话，我就去试着看看改动下simple的序列号跟反序列化，让simple支持多点参数类型。
