### ISSUE TITLE
压测发现内存增长很快，gc压力很大

### ISSUE THREAD

**Issue by cye1024** [weibocom/motan-go#21]

**Comment by cye1024** [comment]
```
      flat  flat%   sum%        cum   cum%
    1.21GB 51.95% 51.95%     1.21GB 51.95%  github.com/weibocom/motan-go.(*Client).buildRequest /Users/yech/tools/gopath/src/github.com/weibocom/motan-go/client.go
    0.47GB 19.94% 71.90%     0.54GB 23.04%  github.com/weibocom/motan-go/protocol.DecodeFromReader /Users/yech/tools/gopath/src/github.com/weibocom/motan-go/protocol/motanProtocol.go
    0.19GB  8.33% 80.23%     0.19GB  8.33%  github.com/weibocom/motan-go/endpoint.(*Channel).NewStream /Users/yech/tools/gopath/src/github.com/weibocom/motan-go/endpoint/motanEndpoint.go
```

**Comment by idevz** [comment]
感谢关注，我们最近正在逐步优化，欢迎持续关注，也欢迎 PR 。

**Comment by rayzhang0603** [comment]
是在压力测试模式下吗？大概多久gc一次？gc的对象主要是request？

**Comment by cye1024** [comment]
是的，压力测试。感觉是有内存泄漏。大概10秒多久gc一次。每次gc之后内存就会跳上去一截
我这是开了15个goroutine，不停访问server的。tps大概2w，gc的时候大概1w。内存会每次gc的时候涨一截。直到内存满了。就卡死了。访问也失败。

**Comment by rayzhang0603** [comment]
我们试着复现一下这个场景，感谢

**Comment by cye1024** [comment]
根据pprof的内存分析结果，大概是
```
github.com/weibocom/motan-go.(*Client).buildRequest
github.com/weibocom/motan-go/protocol.DecodeFromReader
github.com/weibocom/motan-go/protocol.(*Message).Encode
bytes.makeSlice
github.com/weibocom/motan-go/endpoint.(*Channel).NewStream
github.com/weibocom/motan-go/filter.(*AccessLogEndPointFilter).Filter

```
这个几个函数，消耗内存最大。
尤其buildRequest（28%），DecodeFromReader（11%）两个最大。

**Comment by cye1024** [comment]
@rayzhang0603 请问内存问题能复现么？有什么进展么？

**Comment by rayzhang0603** [comment]
这两个是请求的正常消耗，每个请求都会build一个request，request中的对象基本都是指针引用，这块我们也会在评估一下有没有使用对象池的必要。
这周还有一些功能在开发，下周会进行一下复现与分析。

**Comment by cye1024** [comment]
我今天又压了一下，十几分钟，内存涨到30G了。。

**Comment by cye1024** [comment]
@rayzhang0603 好像找到原因了，麻烦确认下：
endpoint/motanEndpoint.go文件 (s *Stream) Send()函数中：
```
    s.sendMsg.Header.RequestID = s.localRequestID
    buf := s.sendMsg.Encode()
    s.sendMsg.Header.RequestID = s.originRequestID 
```
如果originRequestID为0，则此时RequestID被置为0。
而在NewStream时，设置到map中的key是localRequestID：
`c.streams[s.localRequestID] = s`。
由此导致Stream的Close中，
`delete(s.channel.streams, s.sendMsg.Header.RequestID)`，
streams中的stream删除失败，就累积在内存中，导致内存持续增长。

**Comment by rayzhang0603** [comment]
@cye1024 确实存在这个问题，非常感谢！可以提个PR帮忙修复一下，delete时也使用s.localRequestID就可以了

**Comment by cye1024** [comment]
RequestID建议在Client.go中的buildRequest()初始化中给个值。
感觉RequestID应该贯穿整个Client-Server的唯一标签。初始化后，不应该被localRequestID或者originRequestID等其他任何地方赋值。
同时Stream也不需要“originRequestID”与“localRequestID”，只要一个“ID”就可以了。

**Comment by rayzhang0603** [comment]
@cye1024 之所以使用localid和originID是为了方便类似php这样的脚本语言代理时使用，在agent代理时，需要在其他语言client没有传入id是自动生成，所以这部分需要进行保留

**Comment by rayzhang0603** [comment]
使用goclient时，可以在client.go创建reqeust时生成requestid

**Comment by cye1024** [comment]
只看了go客户端，眼光狭隘了，不好意思。
