### ISSUE TITLE
建议增加一个release note

### ISSUE THREAD

**Issue by cye1024** [weibocom/motan-go#41]
每次master更新时候，有个文档说明下更新了什么内容

**Comment by rayzhang0603** [comment]
非常感谢建议～
master更新一般都是pr方式，更新内容可以参考pr中的说明，例如 https://github.com/weibocom/motan-go/pull/39
一般master是迭代主分支，在pr merge前会进行功能测试，后续会在发布新版本时单独发布tag和release，并更新release note
