### ISSUE TITLE
WeiboMesh是否全面开源？

### ISSUE THREAD

**Issue by sundylgz** [weibocom/motan-go#44]

**Comment by rayzhang0603** [comment]
是的，weibo mesh会全面开源。
由于需要与内部不同系统进行适配，我们内部的weibomesh由开源的核心框架+内部适配模块组成，一般通用的功能都会在开源框架中实现，定制的功能会在开源框架中预留扩展点。

**Comment by andyyin** [comment]
目前 java 和 go 是不经过 mesh 的 agent 是吧，另外，还想请教下，如果保证 agent 的可用性，说的是 agent 自身的可用性，如果 agent 挂了，内部这块是怎么处理的？

**Comment by rayzhang0603** [comment]
目前微博内部以php使用agent 正、反向代理方式为主，少部分java和golang在使用agent。后续的方向是大部分java和golang也都会使用agent进行正反向代理，目前正在开发直接通过agent订阅、注册服务的能力，可以大大减少java、golang应用agent时的配置成本。

关于agent可用性，主要有两个方面，一个是agent挂掉时，client通过agent保存的server节点快照进行直连访问，这样可以为agent故障恢复提供一个短暂的窗口期；另一个是通过监控脚本，在agent挂掉时进行自动拉起，保证agent进程持续工作。 同时，agent会定期推送的profile数据，内部也有针对profilet数据的监控报警

**Comment by andyyin** [comment]
感谢回复，期待 weibo mesh 开源
