### ISSUE TITLE
序列化方式问题请教

### ISSUE THREAD

**Issue by colinwdk** [weibocom/motan-go#47]
请问下，大概什么时间能支持复杂的序列化方式（不只有simple的）？

**Comment by colinwdk** [comment]
好的，多谢指点。

**Comment by colinwdk** [comment]
好的，多谢指点。
再请教些问题。是关于配置项的。
1.motan-go的服务端和客户端的配置项是跟motan（https://github.com/weibocom/motan/wiki/zh_configuration）一模一样的吗？
2.client端连接到同一个server端，会产生多个连接吗？
3.如果是多个连接，是通过哪个配置参数限制的？是这个connections参数（0表示共享连接，共享连接是啥意思）吗？
多谢多谢！

**Comment by colinwdk** [comment]
好的，多谢指点。
再请教些问题。是关于配置项的。
1.motan-go的服务端和客户端的配置项是跟motan（https://github.com/weibocom/motan/wiki/zh_configuration）一模一样的吗？
2.同一个client端连接到同一个server端，会产生多个连接吗？
3.如果是多个连接，是通过哪个配置参数限制的？是这个connections参数（0表示共享连接，共享连接是啥意思）吗？
多谢多谢！

**Comment by rayzhang0603** [comment]
1、同名的配置项含义会保持一致，不过go版本目前仅支持一部分配置项
2、一个client链接同一个server会有多个链接，目前固定3个链接，后续会支持`minClientConnection`参数进行配置
3、connections参数目前并未启用。共享链接一般是指一个server端口对外提供不同的service时，相同host：port可以共用链接。java版本中是通过参数`shareChannel`来配置的，目前golang版本暂不支持共享链接。

**Comment by colinwdk** [comment]
多谢！
还有个问题。例如serverdemo.go的例子
	1.mscontext := motan.GetMotanServerContext("./szmotan/motanConf/serverdemo.yaml")
	2.mscontext.RegisterService(&MotanDemoService{}, "")
	3.mscontext.Start(nil)
	4.mscontext.ServicesAvailable()
type MotanDemoService struct{}
上面这些都必须写在package为main里面吗？
我测试如果把MotanDemoService  struct定义到别的package里面就不行了。或者把1,2,3,4写在别的packapge里面也不行，就必须写在main包里面吗？
多谢多谢！

**Comment by colinwdk** [comment]
"我测试如果把MotanDemoService struct定义到别的package里面就不行了"关于这个问题，我知道原因了 应该在配置文件里面的ref指定下的。

**Comment by colinwdk** [comment]
多谢！
还有个问题。例如serverdemo.go的例子
1.mscontext := motan.GetMotanServerContext("./szmotan/motanConf/serverdemo.yaml")
2.mscontext.RegisterService(&MotanDemoService{}, "")
3.mscontext.Start(nil)
4.mscontext.ServicesAvailable()
上面这些都必须写在package为main里面吗？
把1,2,3,4写在别的packapge里面不行，就必须写在main包里面吗？

**Comment by rayzhang0603** [comment]
写在别的package也可以，只需要保证主函数中会调用到mscontext初始化的这部分代码就可以

**Comment by idevz** [comment]
@lexburner 此时需要将 Java Server 的协议指定为 `motan2` 协议，序列化指定为 `simple`，如下面这样：
```xml
    <motan:protocol id="motan2" default="true" name="motan2" serialization="simple"/>
```
关于跨语言的示例我们有个[motan-examples](https://github.com/motan-ecosystem/motan-examples)的示例项目，你可以看下。
