### ISSUE TITLE
调用时超时时间设置问题

### ISSUE THREAD

**Issue by colinwdk** [weibocom/motan-go#96]
想请教下，在调用该函数时mclient.Call(...)，想设置一个超时时间比如100ms 不返回结果，就返回一个err。因为有个业务场景需要这样，不知道有没有什么办法可以实现？

**Comment by rayzhang0603** [comment]
在motan-refer中设置`requestTimeout: 100`就可以，`Call(method string, args []interface{}, reply interface{}) error`这个方法声明就是在请求失败时返回err
